<div class="row padding-2">
<section>
        <h1>O NAS:</h1>
        <p>
            Powstaliśmy w 2009 roku jako zlepek przyjaciół ze sporym doświadczeniem w branży TSL chcących zawojować świat transportowy. Od tego czasu systematycznie poszerzamy grono naszych Pracowników i Partnerów , posiadany tabor a przede wszystkim naszą wiedzę i doświadczenie. Otwieramy nowe oddziały i inwestujemy w młodych , kreatywnych i ciekawych ludzi. Rozwijamy się nie tylko zawodowo, inwestujemy w nasze pasje aby co rano przychodzić do pracy z nowymi pomysłami. Transport traktujemy jako wyzwanie, nie jako rutynę.
        </p>
        <h1>MISJA:</h1>
        <p>
            Misją naszej firmy jest organizacja transportów naszych Klientów w sposób spójny, harmonijny oraz bezproblemowy tak,aby nasze plany transportowe zasługiwały na miano "dzieła sztuki". Dążymy do nawiązywania długoterminowych relacji biznesowych zarówno z naszymi Partnerami jak i Klientami.
        </p>
        <h1>WIZJA:</h1>
        <p>
            Realizujemy nasze usługi transportowe i spedycyjne z pasją oraz na najwyższym poziomie. Współdziałamy z każdym Klientem na zasadach partnerskich w myśl hasła "You create we deliver". W związku z tym pragniemy całkowitej integracji naszych Partnerów biznesowych dysponujących flotą transportową wraz ze zleceniami naszych Klientów tak, aby przepływ ładunków oraz informacji następował w sposób płynny i wygodny dla Klienta.
        </p>
        
</section>
<section class="dokumenty-firmy">
    <div class="col-md-2 col-md-offset-5">
        <a href="<? echo $this->basePath('o-nas/dokumenty')?>"><img src="<? echo $this->basePath('img/icon/download.png')?>">
        <h1>Dokumenty Firmy</h1>
        </a>
    </div>
            
</section>
</div>
<div class="row padding-1"></div>
