<div class="row padding-2">
      <section>
        <h1>TRANSPORT CAŁOPOJAZDOWY NEUTRALNY I SPECJALISTYCZNY</h1>
            <p>Do Państwa dyspozycji oddajemy tabor o ładowności od 1 tony wzwyż:
<ul>
    <li>Busy o DMC do 3,5 tony : plandeki oraz z zabudową sztywną z możliwością wyposażenia w wózek paletowy</li>
    <li>Samochody ciężarowe o ładowności 1,5-10 ton zarówno firany jak zabudowy sztywne z opcją windy oraz wózka paletowego</li>
    <li>Naczepy 13,6 LDM standardowej wysokości lub w opcji Mega (3m wysokości)</li>
    <li>Chłodnie oraz izotermy,</li>
    <li>Naczepy niskopodłogowe praz platformy do przewozu towarów ponadgabarytowych,</li>
    <li>Naczepy do przewozu towarów sypkich oraz pylistych jak wywrotki, naczepy typu walking floor

oraz silosy.</li>
</ul>

</p>
<p>
    Posiadamy wymagane ubezpieczenia zarówno do przewozu ładunków neutralnych jak również ADR,Alkoholi czy elektroniki.
</p>

<p>
    Specjalizujemy się w przewozie odpadów na terenie całej Europy. Posiadany tabor samochodowy oraz umowy ze sprawdzonymi Firmami Przewozowymi pozwalają na przewóz każdego rodzaju ładunku w dogodnym dla Państwa terminie. Wszystkie samochody wyposażone są w telefony bezprzewodowe GSM, co ułatwia przepływ informacji oraz pozwala na kontrolę pozycji samochodu. Dodatkowo nasze pojazdy wyposażone są w system monitorowania GPS Optifleet pozwalający na śledzenie przesyłki online.

</p>

<p>
    Stosujemy umowny system stawek w zależności od ilości i częstotliwości zamówień.
</p>
      </section>
    </div>
<div class="row padding-1"></div>