<div class="row padding-2">
      <section>
        <h1>TRANSPORT CZĘSCIOWY I DROBNICOWY</h1>
        <p>
            Zdarza się, że ładunki przewożone przez nas mają niski tonaż lub wymiary a naszemu Klientowi nie zależy na ekspresowym terminie dostawy. Wówczas taki przewóz możemy wykonać środkiem transportu z możliwością doładunku. Zaletą tego typu rozwiązania jest niższa cena niż w przypadku transportu dedykowanego ponieważ wykorzystując jeden środek transportu możemy w tym samym momencie przewieźć kilka pojedynczych przesyłek. Jednocześnie, nasi Spedytorzy czuwają nad sprawnym i terminowym dostarczeniem każdego z tych ładunków wedle życzenia i zaleceń Klienta. 
        </p>
        <p>
            Ceny tego typu przewozów ustalane są każdorazowo wg konkretnych wymagań Klienta, tak aby za rozsądną cenę zaproponować najlepsze rozwiązanie.  
        </p>
      </section>
    </div>
<div class="row padding-1"></div>