
<div class="row padding-2">
      <section>        
        <h1>Spedycja Drogowa</h1>
        <p>
    Największym marzeniem Da Vinci Team jest sprostać wszystkim wymaganiom naszych Klientów. Niestety nie jesteśmy w stanie tego uczynić korzystając wyłącznie z własnego taboru. Dlatego też nasze usługi obejmują również usługi spedycyjne. Uzyskane licencjeoraz posiadane ubezpieczenia pozwalają naszym Zleceniodawcom i Podwykonawcom czuć się bezpiecznie podczas korzystania z tego rodzaju usług.
</p>

<p>Nasi Przewoźnicy są naszymi Partnerami, często wieloletnimi. Nowi muszą spełniać rygorystyczne standardy współpracy z naszą Firmą. Aktualnie w naszej bazie posiadamy kilka tysięcy sprawdzonych firm transportowych mających swe siedziby na terenie całej Europy.</p>
      </section>
    </div>
<div class="row padding-1"></div>