<div class="row padding-2">
    <section>
    <h1><a name="top"></a>Elastyczni pracownicy</h1>
    <p>
        Naszą Kadrę tworzą specjaliści z wieloletnim doświadczeniem w branży TSL. Wiemy, że ciągły rozwój i podnoszenie kwalifikacji naszych Pracowników wpływa na profesjonalizm działań i jakość naszych usług. Jesteśmy dyspozycyjni 24h zarówno w kwestiach przewozu ładunków jak również jeśli chodzi o kwestie doradcze. W zależności od częstotliwości współpracy oraz potrzeb Klienta dedykujemy do jego obsługi konkretnego Opiekuna Klienta oraz konkretne zasady współpracy . 
    </p>
    </section>
</div>

<div class="row"></div>
