<div class="row">
    <h1>Nasza działność charytatywna</h1>
    
    
    
    <? foreach($charytatywnie as $row) :?>
    
    <div class="col-sm-6 col-md-4">
     <div class="thumbnail">
         <img  src="<?echo $this->basePath('/img/charytatywnie/postaw-na-lewka-2015.jpg') ?>" alt="miiaturka postaw na lewka">
       <div class="caption">
         <h3><?echo $row->tytul?></h3>
         <p><?echo mb_substr($row->opis, 0,150,'UTF-8')?>...</p>
         <p><a href="<? echo $this->basePath('/dzialalnosc-charytatywna/'.$row->id)?>" class="btn btn-primary" role="button">Czytaj więcej</a> </p>
       </div>
     </div>
    </div>
    <? endforeach;?>
    
</div>
<div class="row"></div>