
    <div class="row padding-2">
      <section>
        <img src="<?php echo $this->basePath('img/logo.gif')?>" alt="logo davicni" />
        <h1>YOU CREATE. WE DELIVER</h1>
        
      </section>
    </div>
    <div class="row padding-1" >
      <div class="col-md-6 col-xs-12">
        <h2>Poznaj naszą ofertę</h2>
        <ul class="icon">
            <li><img src="<?php echo $this->basePath('img/icon/next.png')?>" alt="ikona-ozdobnik"><a href="<?php echo $this->basePath('/transport/calopojazdowy')?>">Transport  całopojazdowy neutralny i specjalistyczny</a></li>
            <li><img src="<?php echo $this->basePath('img/icon/next.png')?>" alt="ikona-ozdobnik"><a href="<?php echo $this->basePAth('/transport/czesciowy-i-drobnicowy')?>">Transport częściowy i drobnicowy</a></li>
            <li><img src="<?php echo $this->basePath('img/icon/next.png')?>" alt="ikona-ozdobnik"><a href="<?php echo $this->basePath('/transport/spedycja-drogowa')?>">Spedycja drogowa</a></li>
        </ul>

      </div>
      <div class="col-md-6 hidden-xs" style="padding:0">
        <img src="<?php echo $this->basePath('img/right.jpg')?>" class="img-responsive"/>

      </div>

    </div>

    